# -*- coding: utf-8 -*-
"""

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14VrEymRhgeCGZReATpzmZdc7Syf6N0k6
"""

# GPU
import torch
print(torch.cuda.is_available())
print(torch.cuda.get_device_name(0) if torch.cuda.is_available() else "No GPU")

# Upload files
from google.colab import files
uploaded = files.upload()

# Extract zip file
import zipfile
import os

zip_path = "ai_hw1_colab.zip"
# Extraction directory
extract_dir = "/content/ai_hw1_colab"

with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall(extract_dir)

print("Extraction completed")
print(os.listdir(extract_dir))

# Check files
base_dir = "/content/ai_hw1_colab/ai_hw1_colab"
print("pairs.csv exists:", os.path.exists(os.path.join(base_dir, "pairs.csv")))
print("prompts.json exists:", os.path.exists(os.path.join(base_dir, "prompts.json")))
print("product exists:", os.path.exists(os.path.join(base_dir, "product")))
print("ref exists:", os.path.exists(os.path.join(base_dir, "ref")))


!pip install diffusers==0.24.0 transformers==4.37.0 accelerate==0.26.0 safetensors -q

# Verify data mapping
import os
import json
import pandas as pd

base_dir = "/content/ai_hw1_colab/ai_hw1_colab"
pairs_path = os.path.join(base_dir, "pairs.csv")
prompts_path = os.path.join(base_dir, "prompts.json")
product_dir = os.path.join(base_dir, "product")
ref_dir = os.path.join(base_dir, "ref")

df = pd.read_csv(pairs_path)

with open(prompts_path, "r", encoding="utf-8") as f:
    prompts_data = json.load(f)

print("Number of rows in pairs.csv:", len(df))
print("Number of entries in prompts.json:", len(prompts_data))
print(df.head(3))
print(prompts_data[:2])

# Convert prompts into a lookup table (build prompt_map)
prompt_map = {item["pair_id"]: item["generated_prompt"] for item in prompts_data}
print(list(prompt_map.items())[:2])

# Load SD1.5 and IP-Adapter
import torch
from diffusers import StableDiffusionPipeline
from PIL import Image

device = "cuda"

pipe = StableDiffusionPipeline.from_pretrained(
    "runwayml/stable-diffusion-v1-5",
    torch_dtype=torch.float16,
    safety_checker=None,
    feature_extractor=None,
).to(device)

pipe.load_ip_adapter(
    "h94/IP-Adapter",
    subfolder="models",
    weight_name="ip-adapter_sd15.bin",
)
pipe.set_ip_adapter_scale(0.6)
pipe.enable_attention_slicing()

print(f"diffusers version: {__import__('diffusers').__version__}")
print("Model loading completed")

# Test one image (check whether the T2I pipeline works)
from PIL import Image
import os

row = df.iloc[0]
pair_id = str(row["pair_id"]).zfill(4)
ref_path = os.path.join(ref_dir, row["ref_image"])
product_path = os.path.join(product_dir, row["product_image"])
prompt = prompt_map[pair_id]

ref_image = Image.open(ref_path).convert("RGB").resize((512, 512))
product_image = Image.open(product_path).convert("RGB").resize((512, 512))

generator = torch.Generator(device="cuda").manual_seed(42)

result = pipe(
    prompt=prompt,
    ip_adapter_image=product_image,  
    negative_prompt="blurry, low quality, text, watermark",
    num_inference_steps=20,
    guidance_scale=6.5,
    generator=generator,
).images[0]

result

# Test a few more images and tune parameters
test_prompts = [
    # Original prompt
    prompt_map["0001"],
    # Enhanced poster-style version
    prompt_map["0001"] + ", advertisement poster layout, marketing design, product showcase",
]

for idx, test_prompt in enumerate(test_prompts):
    for seed in [42, 123, 456]:
        product_image = Image.open(
            os.path.join(product_dir, df.iloc[0]["product_image"])
        ).convert("RGB").resize((512, 512))

        generator = torch.Generator(device="cuda").manual_seed(seed)

        result = pipe(
            prompt=test_prompt,
            ip_adapter_image=product_image,
            negative_prompt="blurry, low quality, realistic photo, plain background, no text",
            num_inference_steps=30,      # Increased from 20 to 30
            guidance_scale=8.0,          # Increased from 6.5 to 8.0 for stronger prompt alignment
            generator=generator,
        ).images[0]

        display(result)
        print(f"prompt version={idx+1}, seed={seed}")

import os
from PIL import Image
import torch

output_dir = "/content/ai_hw1_colab/generated_images"
os.makedirs(output_dir, exist_ok=True)

for i, row in df.iterrows():
    pair_id = str(row["pair_id"]).zfill(4)
    product_path = os.path.join(product_dir, row["product_image"])
    prompt = prompt_map.get(pair_id, "product advertisement poster, clean background, professional lighting, high quality, commercial photography")

    if not os.path.exists(product_path):
        print(f"Skip {pair_id}: product image not found")
        continue

    try:
        product_image = Image.open(product_path).convert("RGB").resize((512, 512))

        result = pipe(
            prompt=prompt,
            ip_adapter_image=product_image,
            negative_prompt="blurry, low quality, realistic photo, plain background, no text",
            num_inference_steps=30,
            guidance_scale=8.0,
            generator=torch.Generator(device="cuda").manual_seed(456),
        ).images[0]

        # Resize to 224x224
        result = result.resize((224, 224), Image.LANCZOS)
        result.save(os.path.join(output_dir, f"{pair_id}.jpg"))

        print(f"[{i+1}/100] {pair_id} completed")

    except Exception as e:
        print(f"[{i+1}/100] {pair_id} error：{e}")

print("\nAll done！")

# Download zipped output
import shutil
from google.colab import files

shutil.make_archive("/content/generated_images", "zip", output_dir)
files.download("/content/generated_images.zip")
