# -*- coding: utf-8 -*-
"""

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MN5lxISzihjkRWVGHTpt9jirh2j-aqFc
"""

# 1 - 安裝套件
!pip install torchmetrics[multimodal] torch-fidelity transformers -q

# 2 - 上傳檔案
from google.colab import files

# 依序上傳：generated_images.zip, ref.zip, product.zip, prompts.json, pairs.csv
uploaded = files.upload()


from google.colab import files

uploaded = files.upload()


from google.colab import files

uploaded = files.upload()


from google.colab import files

uploaded = files.upload()


from google.colab import files

uploaded = files.upload()

# 3 - 解壓縮
import zipfile
import os

with zipfile.ZipFile("generated_images.zip", 'r') as z:
    z.extractall("/content/generated")

with zipfile.ZipFile("ref.zip", 'r') as z:
    z.extractall("/content/ref")

with zipfile.ZipFile("product.zip", 'r') as z:
    z.extractall("/content/product")

print("generated:", len(os.listdir("/content/generated")), "張")
print("ref:", len(os.listdir("/content/ref")), "張")
print("product:", len(os.listdir("/content/product")), "張")

# 4 - 讀取資料
import json
import pandas as pd

with open("prompts.json", "r", encoding="utf-8") as f:
    prompts_data = json.load(f)
prompt_map = {item["pair_id"]: item["generated_prompt"] for item in prompts_data}

df = pd.read_csv("pairs.csv")
print("prompts:", len(prompt_map), "筆")
print("pairs:", len(df), "筆")

# 5 - CLIP-Score（generated poster vs editing prompt）
# 參考：https://lightning.ai/docs/torchmetrics/stable/gallery/image/clip_score.html

import torch
import numpy as np
from PIL import Image
from transformers import CLIPProcessor, CLIPModel
import torch.nn.functional as F

device = "cuda" if torch.cuda.is_available() else "cpu"

clip_model = CLIPModel.from_pretrained("openai/clip-vit-base-patch16").to(device)
clip_processor = CLIPProcessor.from_pretrained("openai/clip-vit-base-patch16")
clip_model.eval()

gen_dir = "/content/generated"
scores_prompt = []

for pair_id, prompt in prompt_map.items():
    img_path = os.path.join(gen_dir, f"{pair_id}.jpg")
    if not os.path.exists(img_path):
        continue

    img = Image.open(img_path).convert("RGB")

    inputs = clip_processor(
        text=[prompt],
        images=img,
        return_tensors="pt",
        padding=True,
        truncation=True,
        max_length=77,
    )
    inputs = {k: v.to(device) for k, v in inputs.items()}

    with torch.no_grad():
        outputs = clip_model(**inputs)
        img_feat = F.normalize(outputs.image_embeds, dim=-1)
        txt_feat = F.normalize(outputs.text_embeds, dim=-1)
        score = (img_feat * txt_feat).sum().item()
        scores_prompt.append(score)

print(f"CLIP-Score (generated vs prompt): {sum(scores_prompt)/len(scores_prompt):.4f}")

# Debug - 檢查路徑
import os

print("generated 資料夾內容（前5個）:")
print(os.listdir("/content/generated")[:5])

print("\nproduct 資料夾內容（前5個）:")
print(os.listdir("/content/product")[:5])

print("\ndf 的 product_image 欄位（前5個）:")
print(df["product_image"].head())

# 測試第一筆路徑
row = df.iloc[0]
pair_id = str(row["pair_id"]).zfill(4)
gen_path = f"/content/generated/{pair_id}.jpg"
prod_path = f"/content/product/{row['product_image']}"

print(f"\ngen_path: {gen_path} → exists: {os.path.exists(gen_path)}")
print(f"prod_path: {prod_path} → exists: {os.path.exists(prod_path)}")

# 6 - CLIP visual similarity（generated poster vs product image）
# 參考：https://colab.research.google.com/github/openai/clip/blob/master/notebooks/Interacting_with_CLIP.ipynb
!pip install git+https://github.com/openai/CLIP.git -q

import clip
import torch
from PIL import Image
import torch.nn.functional as F
import os

device = "cuda" if torch.cuda.is_available() else "cpu"
model, preprocess = clip.load("ViT-B/16", device=device)
model.eval()

gen_dir = "/content/generated"
product_dir = "/content/product/product"
cos_scores = []

for _, row in df.iterrows():
    pair_id = str(row["pair_id"]).zfill(4)
    gen_path = os.path.join(gen_dir, f"{pair_id}.jpg")
    prod_path = os.path.join(product_dir, row["product_image"])

    if not os.path.exists(gen_path) or not os.path.exists(prod_path):
        continue

    gen_img = preprocess(Image.open(gen_path).convert("RGB")).unsqueeze(0).to(device)
    prod_img = preprocess(Image.open(prod_path).convert("RGB")).unsqueeze(0).to(device)

    with torch.no_grad():
        gen_feat = model.encode_image(gen_img)
        prod_feat = model.encode_image(prod_img)

        gen_feat = F.normalize(gen_feat, dim=-1)
        prod_feat = F.normalize(prod_feat, dim=-1)

        cos_sim = (gen_feat * prod_feat).sum().item()
        cos_scores.append(cos_sim)

print(f"CLIP visual similarity (generated vs product): {sum(cos_scores)/len(cos_scores):.4f}")

# 7 - KID（generated vs ref）
# 參考：https://github.com/toshas/torch-fidelity

import torch_fidelity
from PIL import Image

# ref 圖片 resize 成 224x224 存一份
ref_resized_dir = "/content/ref_resized"
os.makedirs(ref_resized_dir, exist_ok=True)

ref_dir = "/content/ref/ref"
for fname in os.listdir(ref_dir):
    if fname.lower().endswith(('.jpg', '.png', '.jpeg')):
        img = Image.open(os.path.join(ref_dir, fname)).convert("RGB").resize((224, 224))
        img.save(os.path.join(ref_resized_dir, fname))

print(f"ref resized: {len(os.listdir(ref_resized_dir))} 張")

# 計算 KID
metrics = torch_fidelity.calculate_metrics(
    input1="/content/generated",
    input2=ref_resized_dir,
    kid=True,
    fid=False,
    isc=False,
    cuda=torch.cuda.is_available(),
    kid_subset_size=100,
    verbose=True,
)

print(f"\nKID mean: {metrics['kernel_inception_distance_mean']:.6f}")
print(f"KID std:  {metrics['kernel_inception_distance_std']:.6f}")
print("(越低越好)")

# 8 - 總結
print("=" * 40)
print("Task 1 Metric Summary")
print("=" * 40)
print(f"CLIP-Score (vs prompt):   {sum(scores_prompt)/len(scores_prompt):.4f}")
print(f"CLIP similarity (vs product): {sum(cos_scores)/len(cos_scores):.4f}")
print(f"KID mean: {metrics['kernel_inception_distance_mean']:.6f} (越低越好)")
